accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = 'accountapp'

urlpatterns = [
# 함수는 classname.as_view() 추가
    path('create/', AccountCreateView.as_view(), name='create'),
# 안뜨는게 정상. template설정을 안했기 때문.

# 로그인 설정+ html만들기 (template_name 쓰기)
    path('login/',  LoginView.as_view(template_name='accountapp/login.html'), name='login'),
# 로그아웃 설정(Django 가  다 다해줌)
    path('logout/', LogoutView.as_view(), name='logout'),
#그냥하면 안되기에 <int:pk>(아이디로 가지고 있는 값.키) 넣어주기
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),

    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),

    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),


]

likeapp/urls.py
from django.urls import path

from likeapp.views import LikeArticleView

app_name = "likeapp"

urlpatterns = [

    path('article/<int:article_pk>', LikeArticleView.as_view(), name='article_like'),

]

newproject_1/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

#관리자 계정 만들기, python manage.py createsuperuser
from articleapp.views import ArticleListView

urlpatterns = [
    path('', ArticleListView.as_view(), name='home'), #아무것도 없을 떄

    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('subscribe/', include('subscribeapp.urls')),
    path('likes/', include('likeapp.urls')),

    
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profileapp/urls.py
from django.urls import path

from profileapp.views import ProfileCreationView, ProfileUpdateView

app_name = 'profileapp'

urlpatterns = [
    # as_view 잊지 말것.
    # create 는 없는걸 만드는거라 상관없지만 update 는 있는걸 수정하는거기에 int:pk 지정
    path('create/', ProfileCreationView.as_view(), name='create'),
    path('update/<int:pk>', ProfileUpdateView.as_view(), name='update'),

]

accountapp/models.py
from django.db import models

# Create your models here.

class HelloWorld(models.Model):
    text = models.CharField(max_length=255, null=False)
        # 최대길이 255, 텍스트는 비어있으면 안된다는 선언.
    # 그다음 python mamage.py makemigrations

articleapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.


#onetoonefield : 1대 1
#Foreignkey : 1대 다수
#on_delete = 작성자가 삭제했을때 : 작성자 미상으로 남김
from projectapp.models import Project


class Article(models.Model):
    writer = models.ForeignKey(User, on_delete=models.SET_NULL,
                               related_name='article', null=True)

    project = models.ForeignKey(Project, on_delete=models.SET_NULL, related_name='article', null=True, blank=True)

    title = models.CharField(max_length=200, null=True)
    image = models.ImageField(upload_to='article/', null=True)
    content = models.TextField(null=True)

    created_at = models.DateField(auto_now_add=True, null=True)
    #이러면 지정해주지않아도 시간이 자동으로 입력됨.
    like = models.IntegerField(default=0)

# textfield = 긴 문자열
# 모델 만들었으니 당연히 form도

accountapp/forms.py
from django.contrib.auth.forms import UserCreationForm

#아이디 변경 불가능한 비밀번호 변경방법
class AccountCreationForm(UserCreationForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)


        self.fields['username'].disabled = True

accountapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import render
# Create your views here.
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView
from django.views.generic.list import MultipleObjectMixin

from accountapp.decorators import account_owner_var
from accountapp.forms import AccountCreationForm
from accountapp.models import HelloWorld


#decorater 테스트. Django가 '또' 다해줌
from articleapp.models import Article


# CreateView 불러오기 그래도 어디 있는지 알아만 두면 편함
# User, UserCreationForm 도 불러오기
# class 에서는 "reverse_lazy" 를 쓰는데 함수에서의 reverse 방법과 class 에서의 reverse 방법이 다르기 때문.
class AccountCreateView(CreateView):
    model = User
    form_class = UserCreationForm
    success_url = reverse_lazy('articleapp:list')
    template_name = 'accountapp/create.html'
# 이상 진짜로 간단한 회원가입 로직.
# urls.py에 path 경로 내용 추가


#로그인 시 로그인정보 불러오기
#다음 urls.py에서 라우팅(경로) 설정
class AccountDetailView(DetailView, MultipleObjectMixin):
    model = User
    context_object_name = 'target_User'
    template_name = 'accountapp/detail.html'
    paginate_by = 20

    def get_context_data(self, **kwargs):
        article_list = Article.objects.filter(writer=self.object)
        return super().get_context_data(object_list=article_list, **kwargs)


#decorator사용
owner_var = [login_required, account_owner_var]
@method_decorator(owner_var, 'get')
@method_decorator(owner_var, 'post')  # 이렇게 하면 깔끔함
class AccountUpdateView(UpdateView):
    model = User
    form_class = AccountCreationForm
    #만들었던 form에서 가져옴
    context_object_name = 'target_User'
    #지금은 detail이 안됨. <int:pk>를 지정안했기 때문.
    template_name = 'accountapp/update.html'

    def get_success_url(self):
        return reverse('accountapp:detail', kwargs={'pk':self.object.pk})

#회원탈퇴 기능
@method_decorator(owner_var, 'get')
@method_decorator(owner_var, 'post')
class AccountDeleteView(DeleteView):
    model = User
    context_object_name = 'target_User'
    success_url = reverse_lazy("articleapp:list")
    template_name = 'accountapp/delete.html'

accountapp/templates/accountapp/create.html
{% extends 'base.html' %}
{# 뼈대 그대로 들고오면 됨 #}
{% load bootstrap4 %}
{# bootstrap4 적용 #}

{% block content %}
{# m-5 = 모든 방향으로 마진 설정. 5가 최대임 ㅇㅅㅇ #}
{# 'text-center' = 텍스트 중앙 설정  #}
    <div class="text-center mw-500 m-auto">
        <div class="m-5">
            <h4>
                Sign up
            </h4>
        </div>
        <div>
            <form action="{% url 'accountapp:create' %}" method="post">
{#      이전과 비슷하지만 url사용 + post사용  +csrf_token사용         #}
{#      Django 내에서 이미 설정된 것이 있기에, 일일히 적을 필요 X. 그래서 {{ form }} 만 넣으면 됨         #}
                {% csrf_token %}
                {% bootstrap_form form %}
{#      단순 출력 form을 bootstrap form으로 대체          #}
{#      기본은 블럭형. base.css에서 크기 조정          #}
{#      적용은 최상위 div에 적용시킴 그러나 적용이 안되는 경우가 있는데 적용 안된 css를 로드한 상태. #}
{#      크롬 f12눌러 disable cache하면 css변경한거 적용됨  #}
{#      m-auto 마진 자동 설정. bootstrap에 딸려있음.          #}

{#      한층 더 생성         #}
                <div class="m-5">
                <input type="submit"
                       class="btn btn-dark rounded-pill px-5">
                </div>
            </form>

        </div>
    </div>



{% endblock %}

accountapp/templates/accountapp/delete.html
{% extends 'base.html' %}
{# 늘 그러하듯이 뼈대 그대로 들고오면 됨 #}

{% block content %}
    <div class="text-center mw-500 m-auto">
        <div class="m-5">
            <h4>
                Delete
            </h4>
        </div>
        <div>
            <form action="{% url 'accountapp:delete' pk=target_User.pk %}" method="post">
                {% csrf_token %}

                <div class="m-5">
                <input type="submit"
                       class="btn btn-danger rounded-pill px-5">
                </div>
            </form>

        </div>
    </div>



{% endblock %}

accountapp/templates/accountapp/detail.html
{% extends 'base.html' %}


{% block content %}
    <div class="text-center mw-500 m-auto">
        <div class="m-5">
{#      이제는 프로필이 있는지를 확인하고 username이 아닌 #}
{#      profile의 nickname or message를 가져옴     #}
{#      여기서 profile은 models.py에서 profile이라고 지정을 해뒀기 떄문에 사용가능  #}
{#      src가 이미지를 못가져왔을 때 alt= 가 대체로 텍스트를 불러옴  #}
            {% if target_User.profile %}
                <img src="{{ target_User.profile.image.url }}"
                     class="profile_image m-4"
                     alt="profile image">
                <h2 class="NNS_B">
                    {{ target_User.profile.nickname }}
                    {% if user == target_User %}
                        <a href={% url 'profileapp:update' pk=target_User.profile.pk %} class="material-icons round_button">
{#          round_button css만들기              #}
                                edit
                        </a>
                </h2>
                        {% endif %}
                <h5>{{ target_User.profile.message }}</h5>
            {% else %}
                <h2>
                    <a href={% url 'profileapp:create' %}>
                        Create profile
                    </a>
                </h2>
            {% endif %}
        </div>
{# 주소 입력으로 들어가면 정보가 그대로 노출됨. 막기 위한 용도 #}
        {% if user == target_User %}
            <div>
                <a href="{% url 'accountapp:update' pk=target_User.pk %}"
                class="material-icons round_button mx-1">
                    settings
                </a>
                <a href="{% url 'accountapp:delete' pk=target_User.pk %} "
                class="material-icons round_button mx-1" >
                    delete
                </a>
            </div>
        {% endif %}

    </div>

    <div>
        {% include 'snippets/list_fragment.html' with article_list=object_list %}
    </div>


{% endblock %}

accountapp/templates/accountapp/login.html
{% extends 'base.html' %}
{# create 작성한거 그대로 복붙 #}
{% load bootstrap4 %}
{# create와 똑같이 적용시킴#}

{% block content %}

    <div class="text-center mw-500 m-auto">
        <div class="m-5">
            <h4>
                Login
            </h4>
        </div>
        <div>
            <form action="{% url 'accountapp:login' %}" method="post">
{#      경로 변경 잊지 말것. 근데 이거하면 로그인 설정 끝임          #}
                {% csrf_token %}
                {% bootstrap_form form %}
                <div class="m-5">
                <input type="submit"
                       class="btn btn-dark rounded-pill px-5">
                </div>
            </form>

        </div>
    </div>


{# base.py 에서 로그인관련 설정 + login_Redirect_url 에서 작성#}
{% endblock %}


{# 7/15 #}
{# 1. django-bootstrap 4에서 pip install#}
{# 2. base.py 에서 installed_apps안에  'bootstrap4', 추가#}
{# 3. quickstart 참조 #}

accountapp/templates/accountapp/update.html
{% extends 'base.html' %}
{# 뼈대 그대로 들고오면 됨 #}
{% load bootstrap4 %}
{# bootstrap4 적용 #}

{% block content %}
    <div class="text-center mw-500 m-auto">
        <div class="m-5">
            <h4>
                Update info
            </h4>
        </div>
        <div>
{#      늘 그래왔듯이 그대로 복사 후 붙여놓고 수정      #}
            <form action="{% url 'accountapp:update' pk=target_User.pk %}" method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                <div class="m-5">
                <input type="submit"
                       class="btn btn-dark rounded-pill px-5">
                </div>
            </form>

        </div>
    </div>



{% endblock %}