accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = 'accountapp'

urlpatterns = [
# 함수는 classname.as_view() 추가
    path('create/', AccountCreateView.as_view(), name='create'),
# 안뜨는게 정상. template설정을 안했기 때문.

# 로그인 설정+ html만들기 (template_name 쓰기)
    path('login/',  LoginView.as_view(template_name='accountapp/login.html'), name='login'),
# 로그아웃 설정(Django 가  다 다해줌)
    path('logout/', LogoutView.as_view(), name='logout'),
#그냥하면 안되기에 <int:pk>(아이디로 가지고 있는 값.키) 넣어주기
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),

    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),

    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),


]

articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleListView

app_name = 'articleapp'

urlpatterns = [
    path('list/', ArticleListView.as_view(), name='list'),
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    #detail은 어떤 게시글을 수정, 삭제 등을 해야 하므로
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),






]

likeapp/urls.py
from django.urls import path

from likeapp.views import LikeArticleView

app_name = "likeapp"

urlpatterns = [

    path('article/<int:article_pk>', LikeArticleView.as_view(), name='article_like'),

]

newproject_1/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

#관리자 계정 만들기, python manage.py createsuperuser
from articleapp.views import ArticleListView

urlpatterns = [
    path('', ArticleListView.as_view(), name='home'), #아무것도 없을 떄

    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('subscribe/', include('subscribeapp.urls')),
    path('likes/', include('likeapp.urls')),

    
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projectapp/urls.py
from django.urls import path

from projectapp.views import ProjectCreateView, ProjectDetailView, ProjectListView

app_name = 'projectapp'

urlpatterns = [
    path('create/', ProjectCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ProjectDetailView.as_view(), name='detail'),
    path('list/', ProjectListView.as_view(), name='list'),

]

subscribeapp/urls.py
from django.urls import path

from subscribeapp.views import SubscriptionView, SubscriptionListView

app_name = 'subscribeapp'

urlpatterns = [

    path('subscribe/<int:project_pk>', SubscriptionView.as_view(), name='subscribe'),
    path('list/', SubscriptionListView.as_view(), name='list'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
{#여기서 font size를 조절하면 rem설정값이 바뀜.#}


{% include 'head.html' %}

{#글꼴 변경#}
<body style="font-family: 'NanumSquareR">

{% include 'header.html' %}

<hr>

{# 여기서 messages는 django기본제공이라 언제든 들고오기 가능 #}
{% for message in messages %}
    <div class="text-center">
        <div class="btn btn-{{ message.tags }} rounded-pill px-5">
           {{ message }}
        </div>
    </div>
{% endfor %}

{% block content %}
{% endblock %}

<hr>

{% include 'footer.html' %}

{#    <h1>Hello World ㅇㅅㅇ</h1>#}
{#    <p>What are you doing?</p>#}
{#    <footer>No Copyright ??? Not right reserved?</footer>#}
</body>
</html>

templates/footer.html
<div style="text-align: center;">
        <div class="sub_marge">
            <span>공지사항</span>
            <span>이메일</span>
            <span>소개</span>
            <span>문의</span>
        </div>
        <div class="sub_logo">
            <h5 style="font-size: 15px">program</h5>

        </div>
</div>

templates/head.html
{% load static %} {# staic 폴더를 미리 로드함. 그리고 경로가 어디 있는지를 알려줘야함 settings.py에있는 밑에 django코드  복사 #}



<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initialscale=1.0, shrink-to-fit=no">
    <title>Welcome</title>
    {# bootstrap link #}
    {# 들어가서 css파일 copy하기#}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    {#  구글폰트 링크  #}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">

    {#  static 파일 링크. 이건 직접 입력해야함 그리고 추가로 해야할 것이 있음. #}
    <link rel="stylesheet", type="text/css", href="{% static 'base.css' %}">

    {#  아이콘 링크  #}
    <link href="https://fonts.googleapis.com/css2?family=Material+Icons"
      rel="stylesheet">


{#  복붙하자  #}
    <style>
        @font-face {
            font-family: 'NanumSquareR';
            src: local('NanumSquareR'),
            url("{% static 'fonts/NanumSquareR.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareEB';
            src: local('NanumSquareEB'),
            url("{% static 'fonts/NanumSquareEB.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareB';
            src: local('NanumSquareB'),
            url("{% static 'fonts/NanumSquareB.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareL';
            src: local('NanumSquareL'),
            url("{% static 'fonts/NanumSquareL.otf' %}") format("opentype");
        }
    </style>

</head>

templates/header.html
<div style="text-align: center;">
    <div class="main_logo">
        <h1>
            <a href="{% url 'home' %}">
                programmer
            </a>
        </h1>

    </div>
    <div class="main_marge">
        <span class="mx-2">
            <a href="{% url 'articleapp:list' %}">
                Articles
            </a>
        </span>
        <span class="mx-2">
            <a href="{% url 'projectapp:list' %}">
                Projects
            </a>
        </span>
    {% if user.is_authenticated %}
        <span class="mx-2">
            <a href="{% url 'subscribeapp:list' %}">
                Subscription
            </a>
        </span>
    {% endif %}
{#  로그인 안한 사용자에게만 보여야함    #}
        {%  if not user.is_authenticated %}
        <span class="mx-2">
            <a href="{% url 'accountapp:login' %}">
                로그인
            </a>
{#      알아서 경로를 잡아줌      #}
        </span>
        <span class="mx-2">
            <a href="{% url 'accountapp:create' %}">
                회원가입
            </a>
        </span>
{#  END      #}
        {% else %}
        <span class="mx-2">
            <a href="{% url "accountapp:logout" %}">
                로그아웃
            </a>
        </span>
        <span class="mx-2">
{#  pk값을 추가로 넣어야함. 접근하는 user의 primary key값 입력     #}
            <a href="{% url "accountapp:detail" pk=user.pk %}">
                내 페이지
            </a>
        </span class=mx-2>
        {% endif %}
{#  endfor처럼 명시를 해줘야함  #}
        <span class="mx-2">nav5</span>
    </div>

</div>